# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Base_Block_Diagram/Base_Block_Diagram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram || ORIG_REF_NAME==Base_Block_Diagram} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_processing_system7_0_0/Base_Block_Diagram_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_processing_system7_0_0 || ORIG_REF_NAME==Base_Block_Diagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_rst_ps7_0_100M_0/Base_Block_Diagram_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_rst_ps7_0_100M_0 || ORIG_REF_NAME==Base_Block_Diagram_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_axi_gpio_0_0/Base_Block_Diagram_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_axi_gpio_0_0 || ORIG_REF_NAME==Base_Block_Diagram_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_ps7_0_axi_periph_0/Base_Block_Diagram_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==Base_Block_Diagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_xbar_0/Base_Block_Diagram_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_xbar_0 || ORIG_REF_NAME==Base_Block_Diagram_xbar_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_rayTI_0_0/Base_Block_Diagram_rayTI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_rayTI_0_0 || ORIG_REF_NAME==Base_Block_Diagram_rayTI_0_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_auto_pc_0/Base_Block_Diagram_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_auto_pc_0 || ORIG_REF_NAME==Base_Block_Diagram_auto_pc_0} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_auto_pc_1/Base_Block_Diagram_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_auto_pc_1 || ORIG_REF_NAME==Base_Block_Diagram_auto_pc_1} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_auto_pc_2/Base_Block_Diagram_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_auto_pc_2 || ORIG_REF_NAME==Base_Block_Diagram_auto_pc_2} -quiet] -quiet

# IP: bd/Base_Block_Diagram/ip/Base_Block_Diagram_auto_pc_3/Base_Block_Diagram_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Base_Block_Diagram_auto_pc_3 || ORIG_REF_NAME==Base_Block_Diagram_auto_pc_3} -quiet] -quiet

# XDC: bd/Base_Block_Diagram/Base_Block_Diagram_ooc.xdc
