
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrayti.h"

/*
* The configuration table for devices
*/

XRayti_Config XRayti_ConfigTable[XPAR_XRAYTI_NUM_INSTANCES] =
{
	{
		XPAR_RAYTI_0_DEVICE_ID,
		XPAR_RAYTI_0_S_AXI_RET_BUNDLE_BASEADDR
	}
};


