// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dotProduct_2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dotProduct_2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dotProduct_2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<23> dotProduct_2::ap_ST_fsm_state1 = "1";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state2 = "10";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state3 = "100";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state4 = "1000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state5 = "10000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state6 = "100000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state7 = "1000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state8 = "10000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state9 = "100000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state10 = "1000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state11 = "10000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state12 = "100000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<23> dotProduct_2::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<32> dotProduct_2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dotProduct_2::ap_const_lv1_0 = "0";
const sc_lv<3> dotProduct_2::ap_const_lv3_0 = "000";
const sc_lv<2> dotProduct_2::ap_const_lv2_0 = "00";
const sc_lv<4> dotProduct_2::ap_const_lv4_0 = "0000";
const sc_lv<32> dotProduct_2::ap_const_lv32_6 = "110";
const sc_lv<32> dotProduct_2::ap_const_lv32_D = "1101";
const sc_lv<32> dotProduct_2::ap_const_lv32_1 = "1";
const sc_lv<32> dotProduct_2::ap_const_lv32_8 = "1000";
const sc_lv<32> dotProduct_2::ap_const_lv32_7 = "111";
const sc_lv<32> dotProduct_2::ap_const_lv32_C = "1100";
const sc_lv<32> dotProduct_2::ap_const_lv32_11 = "10001";
const sc_lv<32> dotProduct_2::ap_const_lv32_9 = "1001";
const sc_lv<32> dotProduct_2::ap_const_lv32_E = "1110";
const sc_lv<32> dotProduct_2::ap_const_lv32_12 = "10010";
const sc_lv<32> dotProduct_2::ap_const_lv32_F = "1111";
const sc_lv<32> dotProduct_2::ap_const_lv32_10 = "10000";
const sc_lv<32> dotProduct_2::ap_const_lv32_13 = "10011";
const sc_lv<32> dotProduct_2::ap_const_lv32_14 = "10100";
const sc_lv<32> dotProduct_2::ap_const_lv32_15 = "10101";
const sc_lv<32> dotProduct_2::ap_const_lv32_16 = "10110";
const bool dotProduct_2::ap_const_boolean_1 = true;

dotProduct_2::dotProduct_2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    rayTI_fadd_32ns_3dEe_U36 = new rayTI_fadd_32ns_3dEe<1,5,32,32,32>("rayTI_fadd_32ns_3dEe_U36");
    rayTI_fadd_32ns_3dEe_U36->clk(ap_clk);
    rayTI_fadd_32ns_3dEe_U36->reset(ap_rst);
    rayTI_fadd_32ns_3dEe_U36->din0(grp_fu_112_p0);
    rayTI_fadd_32ns_3dEe_U36->din1(grp_fu_112_p1);
    rayTI_fadd_32ns_3dEe_U36->ce(grp_fu_112_ce);
    rayTI_fadd_32ns_3dEe_U36->dout(grp_fu_112_p2);
    rayTI_fmul_32ns_3cud_U37 = new rayTI_fmul_32ns_3cud<1,4,32,32,32>("rayTI_fmul_32ns_3cud_U37");
    rayTI_fmul_32ns_3cud_U37->clk(ap_clk);
    rayTI_fmul_32ns_3cud_U37->reset(ap_rst);
    rayTI_fmul_32ns_3cud_U37->din0(grp_fu_116_p0);
    rayTI_fmul_32ns_3cud_U37->din1(grp_fu_116_p1);
    rayTI_fmul_32ns_3cud_U37->ce(ap_var_for_const0);
    rayTI_fmul_32ns_3cud_U37->dout(grp_fu_116_p2);
    rayTI_fmul_32ns_3cud_U38 = new rayTI_fmul_32ns_3cud<1,4,32,32,32>("rayTI_fmul_32ns_3cud_U38");
    rayTI_fmul_32ns_3cud_U38->clk(ap_clk);
    rayTI_fmul_32ns_3cud_U38->reset(ap_rst);
    rayTI_fmul_32ns_3cud_U38->din0(Vec3_x_addr_8_read_reg_189);
    rayTI_fmul_32ns_3cud_U38->din1(v_y_read);
    rayTI_fmul_32ns_3cud_U38->ce(ap_var_for_const0);
    rayTI_fmul_32ns_3cud_U38->dout(grp_fu_121_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Vec3_float_x_blk_n_AR);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_Vec3_float_x_ARREADY );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Vec3_float_x_blk_n_R);
    sensitive << ( m_axi_Vec3_float_x_RVALID );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_ap_return);
    sensitive << ( grp_fu_112_p2 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_grp_fu_112_ce);
    sensitive << ( m_axi_Vec3_float_x_RVALID );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_grp_fu_112_p0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( reg_127 );
    sensitive << ( tmp_11_reg_219 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_112_p1);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( reg_127 );
    sensitive << ( tmp_s_reg_204 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_fu_116_p0);
    sensitive << ( Vec3_x_addr_9_read_reg_184 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( Vec3_x_addr_read_reg_209 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_grp_fu_116_p1);
    sensitive << ( v_x_read );
    sensitive << ( v_z_read );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_m_axi_Vec3_float_x_ARADDR);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_Vec3_float_x_ARREADY );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln95_2_fu_133_p1 );
    sensitive << ( zext_ln95_1_fu_144_p1 );
    sensitive << ( zext_ln95_fu_155_p1 );

    SC_METHOD(thread_m_axi_Vec3_float_x_ARBURST);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARCACHE);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARID);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARLEN);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_Vec3_float_x_ARREADY );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_m_axi_Vec3_float_x_ARLOCK);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARPROT);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARQOS);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARREGION);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARSIZE);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARUSER);

    SC_METHOD(thread_m_axi_Vec3_float_x_ARVALID);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_Vec3_float_x_ARREADY );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_m_axi_Vec3_float_x_AWADDR);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWBURST);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWCACHE);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWID);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWLEN);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWLOCK);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWPROT);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWQOS);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWREGION);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWSIZE);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWUSER);

    SC_METHOD(thread_m_axi_Vec3_float_x_AWVALID);

    SC_METHOD(thread_m_axi_Vec3_float_x_BREADY);

    SC_METHOD(thread_m_axi_Vec3_float_x_RREADY);
    sensitive << ( m_axi_Vec3_float_x_RVALID );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_m_axi_Vec3_float_x_WDATA);

    SC_METHOD(thread_m_axi_Vec3_float_x_WID);

    SC_METHOD(thread_m_axi_Vec3_float_x_WLAST);

    SC_METHOD(thread_m_axi_Vec3_float_x_WSTRB);

    SC_METHOD(thread_m_axi_Vec3_float_x_WUSER);

    SC_METHOD(thread_m_axi_Vec3_float_x_WVALID);

    SC_METHOD(thread_zext_ln95_1_fu_144_p1);
    sensitive << ( Vec3_float_y_offset );

    SC_METHOD(thread_zext_ln95_2_fu_133_p1);
    sensitive << ( Vec3_float_x_offset );

    SC_METHOD(thread_zext_ln95_fu_155_p1);
    sensitive << ( Vec3_float_z_offset );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( m_axi_Vec3_float_x_ARREADY );
    sensitive << ( m_axi_Vec3_float_x_RVALID );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000001";
    ap_return_preg = "00000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dotProduct_2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWVALID, "(port)m_axi_Vec3_float_x_AWVALID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWREADY, "(port)m_axi_Vec3_float_x_AWREADY");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWADDR, "(port)m_axi_Vec3_float_x_AWADDR");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWID, "(port)m_axi_Vec3_float_x_AWID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWLEN, "(port)m_axi_Vec3_float_x_AWLEN");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWSIZE, "(port)m_axi_Vec3_float_x_AWSIZE");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWBURST, "(port)m_axi_Vec3_float_x_AWBURST");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWLOCK, "(port)m_axi_Vec3_float_x_AWLOCK");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWCACHE, "(port)m_axi_Vec3_float_x_AWCACHE");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWPROT, "(port)m_axi_Vec3_float_x_AWPROT");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWQOS, "(port)m_axi_Vec3_float_x_AWQOS");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWREGION, "(port)m_axi_Vec3_float_x_AWREGION");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_AWUSER, "(port)m_axi_Vec3_float_x_AWUSER");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WVALID, "(port)m_axi_Vec3_float_x_WVALID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WREADY, "(port)m_axi_Vec3_float_x_WREADY");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WDATA, "(port)m_axi_Vec3_float_x_WDATA");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WSTRB, "(port)m_axi_Vec3_float_x_WSTRB");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WLAST, "(port)m_axi_Vec3_float_x_WLAST");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WID, "(port)m_axi_Vec3_float_x_WID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_WUSER, "(port)m_axi_Vec3_float_x_WUSER");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARVALID, "(port)m_axi_Vec3_float_x_ARVALID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARREADY, "(port)m_axi_Vec3_float_x_ARREADY");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARADDR, "(port)m_axi_Vec3_float_x_ARADDR");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARID, "(port)m_axi_Vec3_float_x_ARID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARLEN, "(port)m_axi_Vec3_float_x_ARLEN");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARSIZE, "(port)m_axi_Vec3_float_x_ARSIZE");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARBURST, "(port)m_axi_Vec3_float_x_ARBURST");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARLOCK, "(port)m_axi_Vec3_float_x_ARLOCK");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARCACHE, "(port)m_axi_Vec3_float_x_ARCACHE");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARPROT, "(port)m_axi_Vec3_float_x_ARPROT");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARQOS, "(port)m_axi_Vec3_float_x_ARQOS");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARREGION, "(port)m_axi_Vec3_float_x_ARREGION");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_ARUSER, "(port)m_axi_Vec3_float_x_ARUSER");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RVALID, "(port)m_axi_Vec3_float_x_RVALID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RREADY, "(port)m_axi_Vec3_float_x_RREADY");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RDATA, "(port)m_axi_Vec3_float_x_RDATA");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RLAST, "(port)m_axi_Vec3_float_x_RLAST");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RID, "(port)m_axi_Vec3_float_x_RID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RUSER, "(port)m_axi_Vec3_float_x_RUSER");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_RRESP, "(port)m_axi_Vec3_float_x_RRESP");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_BVALID, "(port)m_axi_Vec3_float_x_BVALID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_BREADY, "(port)m_axi_Vec3_float_x_BREADY");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_BRESP, "(port)m_axi_Vec3_float_x_BRESP");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_BID, "(port)m_axi_Vec3_float_x_BID");
    sc_trace(mVcdFile, m_axi_Vec3_float_x_BUSER, "(port)m_axi_Vec3_float_x_BUSER");
    sc_trace(mVcdFile, Vec3_float_x_offset, "(port)Vec3_float_x_offset");
    sc_trace(mVcdFile, Vec3_float_y_offset, "(port)Vec3_float_y_offset");
    sc_trace(mVcdFile, Vec3_float_z_offset, "(port)Vec3_float_z_offset");
    sc_trace(mVcdFile, v_x_read, "(port)v_x_read");
    sc_trace(mVcdFile, v_y_read, "(port)v_y_read");
    sc_trace(mVcdFile, v_z_read, "(port)v_z_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, Vec3_float_x_blk_n_AR, "Vec3_float_x_blk_n_AR");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, Vec3_float_x_blk_n_R, "Vec3_float_x_blk_n_R");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_116_p2, "grp_fu_116_p2");
    sc_trace(mVcdFile, reg_127, "reg_127");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, Vec3_x_addr_9_read_reg_184, "Vec3_x_addr_9_read_reg_184");
    sc_trace(mVcdFile, Vec3_x_addr_8_read_reg_189, "Vec3_x_addr_8_read_reg_189");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_121_p2, "grp_fu_121_p2");
    sc_trace(mVcdFile, tmp_s_reg_204, "tmp_s_reg_204");
    sc_trace(mVcdFile, Vec3_x_addr_read_reg_209, "Vec3_x_addr_read_reg_209");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, grp_fu_112_p2, "grp_fu_112_p2");
    sc_trace(mVcdFile, tmp_11_reg_219, "tmp_11_reg_219");
    sc_trace(mVcdFile, zext_ln95_2_fu_133_p1, "zext_ln95_2_fu_133_p1");
    sc_trace(mVcdFile, zext_ln95_1_fu_144_p1, "zext_ln95_1_fu_144_p1");
    sc_trace(mVcdFile, zext_ln95_fu_155_p1, "zext_ln95_fu_155_p1");
    sc_trace(mVcdFile, grp_fu_112_p0, "grp_fu_112_p0");
    sc_trace(mVcdFile, grp_fu_112_p1, "grp_fu_112_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, grp_fu_116_p0, "grp_fu_116_p0");
    sc_trace(mVcdFile, grp_fu_116_p1, "grp_fu_116_p1");
    sc_trace(mVcdFile, grp_fu_112_ce, "grp_fu_112_ce");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dotProduct_2::~dotProduct_2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete rayTI_fadd_32ns_3dEe_U36;
    delete rayTI_fmul_32ns_3cud_U37;
    delete rayTI_fmul_32ns_3cud_U38;
}

void dotProduct_2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dotProduct_2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv32_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
            ap_return_preg = grp_fu_112_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
        Vec3_x_addr_8_read_reg_189 = m_axi_Vec3_float_x_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
        Vec3_x_addr_9_read_reg_184 = m_axi_Vec3_float_x_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
        Vec3_x_addr_read_reg_209 = m_axi_Vec3_float_x_RDATA.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        reg_127 = grp_fu_116_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        tmp_11_reg_219 = grp_fu_112_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_s_reg_204 = grp_fu_121_p2.read();
    }
}

void dotProduct_2::thread_Vec3_float_x_blk_n_AR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)))) {
        Vec3_float_x_blk_n_AR = m_axi_Vec3_float_x_ARREADY.read();
    } else {
        Vec3_float_x_blk_n_AR = ap_const_logic_1;
    }
}

void dotProduct_2::thread_Vec3_float_x_blk_n_R() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        Vec3_float_x_blk_n_R = m_axi_Vec3_float_x_RVALID.read();
    } else {
        Vec3_float_x_blk_n_R = ap_const_logic_1;
    }
}

void dotProduct_2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dotProduct_2::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void dotProduct_2::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dotProduct_2::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dotProduct_2::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void dotProduct_2::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void dotProduct_2::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void dotProduct_2::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void dotProduct_2::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void dotProduct_2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dotProduct_2::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void dotProduct_2::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void dotProduct_2::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void dotProduct_2::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void dotProduct_2::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dotProduct_2::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void dotProduct_2::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void dotProduct_2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dotProduct_2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dotProduct_2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dotProduct_2::thread_ap_return() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        ap_return = grp_fu_112_p2.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void dotProduct_2::thread_grp_fu_112_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()))) {
        grp_fu_112_ce = ap_const_logic_1;
    } else {
        grp_fu_112_ce = ap_const_logic_0;
    }
}

void dotProduct_2::thread_grp_fu_112_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_112_p0 = tmp_11_reg_219.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_112_p0 = reg_127.read();
    } else {
        grp_fu_112_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dotProduct_2::thread_grp_fu_112_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        grp_fu_112_p1 = reg_127.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        grp_fu_112_p1 = tmp_s_reg_204.read();
    } else {
        grp_fu_112_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dotProduct_2::thread_grp_fu_116_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_116_p0 = Vec3_x_addr_read_reg_209.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_116_p0 = Vec3_x_addr_9_read_reg_184.read();
    } else {
        grp_fu_116_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dotProduct_2::thread_grp_fu_116_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        grp_fu_116_p1 = v_z_read.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        grp_fu_116_p1 = v_x_read.read();
    } else {
        grp_fu_116_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARADDR() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1))) {
        m_axi_Vec3_float_x_ARADDR =  (sc_lv<32>) (zext_ln95_fu_155_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1))) {
        m_axi_Vec3_float_x_ARADDR =  (sc_lv<32>) (zext_ln95_1_fu_144_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_Vec3_float_x_ARREADY.read())))) {
        m_axi_Vec3_float_x_ARADDR =  (sc_lv<32>) (zext_ln95_2_fu_133_p1.read());
    } else {
        m_axi_Vec3_float_x_ARADDR = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARBURST() {
    m_axi_Vec3_float_x_ARBURST = ap_const_lv2_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARCACHE() {
    m_axi_Vec3_float_x_ARCACHE = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARID() {
    m_axi_Vec3_float_x_ARID = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARLEN() {
    m_axi_Vec3_float_x_ARLEN = ap_const_lv32_1;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARLOCK() {
    m_axi_Vec3_float_x_ARLOCK = ap_const_lv2_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARPROT() {
    m_axi_Vec3_float_x_ARPROT = ap_const_lv3_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARQOS() {
    m_axi_Vec3_float_x_ARQOS = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARREGION() {
    m_axi_Vec3_float_x_ARREGION = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARSIZE() {
    m_axi_Vec3_float_x_ARSIZE = ap_const_lv3_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARUSER() {
    m_axi_Vec3_float_x_ARUSER = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_ARVALID() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_Vec3_float_x_ARREADY.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1)))) {
        m_axi_Vec3_float_x_ARVALID = ap_const_logic_1;
    } else {
        m_axi_Vec3_float_x_ARVALID = ap_const_logic_0;
    }
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWADDR() {
    m_axi_Vec3_float_x_AWADDR = ap_const_lv32_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWBURST() {
    m_axi_Vec3_float_x_AWBURST = ap_const_lv2_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWCACHE() {
    m_axi_Vec3_float_x_AWCACHE = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWID() {
    m_axi_Vec3_float_x_AWID = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWLEN() {
    m_axi_Vec3_float_x_AWLEN = ap_const_lv32_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWLOCK() {
    m_axi_Vec3_float_x_AWLOCK = ap_const_lv2_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWPROT() {
    m_axi_Vec3_float_x_AWPROT = ap_const_lv3_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWQOS() {
    m_axi_Vec3_float_x_AWQOS = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWREGION() {
    m_axi_Vec3_float_x_AWREGION = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWSIZE() {
    m_axi_Vec3_float_x_AWSIZE = ap_const_lv3_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWUSER() {
    m_axi_Vec3_float_x_AWUSER = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_AWVALID() {
    m_axi_Vec3_float_x_AWVALID = ap_const_logic_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_BREADY() {
    m_axi_Vec3_float_x_BREADY = ap_const_logic_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_RREADY() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1)))) {
        m_axi_Vec3_float_x_RREADY = ap_const_logic_1;
    } else {
        m_axi_Vec3_float_x_RREADY = ap_const_logic_0;
    }
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WDATA() {
    m_axi_Vec3_float_x_WDATA = ap_const_lv32_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WID() {
    m_axi_Vec3_float_x_WID = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WLAST() {
    m_axi_Vec3_float_x_WLAST = ap_const_logic_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WSTRB() {
    m_axi_Vec3_float_x_WSTRB = ap_const_lv4_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WUSER() {
    m_axi_Vec3_float_x_WUSER = ap_const_lv1_0;
}

void dotProduct_2::thread_m_axi_Vec3_float_x_WVALID() {
    m_axi_Vec3_float_x_WVALID = ap_const_logic_0;
}

void dotProduct_2::thread_zext_ln95_1_fu_144_p1() {
    zext_ln95_1_fu_144_p1 = esl_zext<64,30>(Vec3_float_y_offset.read());
}

void dotProduct_2::thread_zext_ln95_2_fu_133_p1() {
    zext_ln95_2_fu_133_p1 = esl_zext<64,30>(Vec3_float_x_offset.read());
}

void dotProduct_2::thread_zext_ln95_fu_155_p1() {
    zext_ln95_fu_155_p1 = esl_zext<64,30>(Vec3_float_z_offset.read());
}

void dotProduct_2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, m_axi_Vec3_float_x_ARREADY.read())))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_ARREADY.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(m_axi_Vec3_float_x_RVALID.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<23>) ("XXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

