# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /run/media/nikolas/Linux_Data/Git_Repos/RayTracing_FPGA/hardware_implementation/base_hardware_project/Base_System_Vivado_project/Base_System_Vivado_project.srcs/sources_1/bd/Base_Block_Diagram/ip/Base_Block_Diagram_processing_system7_0_0/Base_Block_Diagram_processing_system7_0_0.xci
# IP: The module: 'Base_Block_Diagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/Git_Repos/RayTracing_FPGA/hardware_implementation/base_hardware_project/Base_System_Vivado_project/Base_System_Vivado_project.srcs/sources_1/bd/Base_Block_Diagram/ip/Base_Block_Diagram_processing_system7_0_0/Base_Block_Diagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Block_Diagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /run/media/nikolas/Linux_Data/Git_Repos/RayTracing_FPGA/hardware_implementation/base_hardware_project/Base_System_Vivado_project/Base_System_Vivado_project.srcs/sources_1/bd/Base_Block_Diagram/ip/Base_Block_Diagram_processing_system7_0_0/Base_Block_Diagram_processing_system7_0_0.xci
# IP: The module: 'Base_Block_Diagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /run/media/nikolas/Linux_Data/Git_Repos/RayTracing_FPGA/hardware_implementation/base_hardware_project/Base_System_Vivado_project/Base_System_Vivado_project.srcs/sources_1/bd/Base_Block_Diagram/ip/Base_Block_Diagram_processing_system7_0_0/Base_Block_Diagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Base_Block_Diagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
